export const THEMES: Record<string, Record<string, string>> = {
    green: {
      '--ap-primary-40'  : '#156c38',
      '--ap-primary-100' : '#ffffff',
      '--login-bg-1'     : '#c9ebcc',
      '--main-menu-bg-1' : '#00602e',
      '--sub-menu-bg-1'  : '#eaffe9',
      '--footer-bg-1'    : '#e9fce8',
      '--side-nav-bg-1'  : '#f3f5f4',
      '--main-menu-tx-1' : '#ffffff',
      '--sub-menu-tx-1'  : '#464444',
      '--menu-active-bg-1': '#d9f39c',
      '--menu-active-tx-1' : '#00796b',
      '--main-body-bg-1'   : '#e4e3ef',
      '--breadcrumb-bg-1'  : '#ffffff',
    },
    blue: {
      '--ap-primary-40'  : '#0f797c',
      '--ap-primary-100' : '#ffffff',
      '--login-bg-1'     : '#c2e9eb',
      '--main-menu-bg-1' : '#73cccf',
      '--sub-menu-bg-1'  : '#d2f4f5',
      '--footer-bg-1'    : '#e1f9fa',
      '--side-nav-bg-1'  : '#f3f5f4',
      '--main-menu-tx-1' : '#ffffff',
      '--sub-menu-tx-1'  : '#464444',
      '--menu-active-bg-1': '#d9f39c',
      '--menu-active-tx-1' : '#00796b',
      '--main-body-bg-1'   : '#e4e3ef',
      '--breadcrumb-bg-1'  : '#ffffff',
    },
  };